version: 0.2
phases:
  build:
    commands:
      - echo Packaging JAR file...
      - mvn clean package
  post_build:
    commands:
      - echo Build complete.
artifacts:
  files:
    - target/enablix-app.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: no